// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjBSKe9d7N54zOq9k-BJsttKxOVEXc_h8',
    appId: '1:683436057305:web:9071e1d7f72a4d695e14c8',
    messagingSenderId: '683436057305',
    projectId: 'hello34-8ea99',
    authDomain: 'hello34-8ea99.firebaseapp.com',
    storageBucket: 'hello34-8ea99.firebasestorage.app',
    measurementId: 'G-S19EKTQW0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEQSoTiAyCpZy1Ni3Yc-osOrr3UNmNMnY',
    appId: '1:683436057305:android:7560d7a66ac84b5e5e14c8',
    messagingSenderId: '683436057305',
    projectId: 'hello34-8ea99',
    storageBucket: 'hello34-8ea99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGHGptoAiNHQPRuEzURD4C6PVl49Xxd2c',
    appId: '1:683436057305:ios:81a83f3bf5dc01365e14c8',
    messagingSenderId: '683436057305',
    projectId: 'hello34-8ea99',
    storageBucket: 'hello34-8ea99.firebasestorage.app',
    iosBundleId: 'com.example.callibrationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGHGptoAiNHQPRuEzURD4C6PVl49Xxd2c',
    appId: '1:683436057305:ios:81a83f3bf5dc01365e14c8',
    messagingSenderId: '683436057305',
    projectId: 'hello34-8ea99',
    storageBucket: 'hello34-8ea99.firebasestorage.app',
    iosBundleId: 'com.example.callibrationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjBSKe9d7N54zOq9k-BJsttKxOVEXc_h8',
    appId: '1:683436057305:web:c3fa05a6b7afc2dc5e14c8',
    messagingSenderId: '683436057305',
    projectId: 'hello34-8ea99',
    authDomain: 'hello34-8ea99.firebaseapp.com',
    storageBucket: 'hello34-8ea99.firebasestorage.app',
    measurementId: 'G-Y36HFKHSR1',
  );
}
